all: brute horspool presort

brute: brute.c
	gcc -o brute brute.c

horspool: horspool.c
	gcc -o horspool horspool.c

presort: presort.c
	gcc -o presort presort.c

clean:
	rm -r -f bin *.o *.dump brute horspool presort
